<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain\Domain.fs" />
    <Compile Include="Infrastructure\Neo4j.fs" />
    <Compile Include="Infrastructure\Schema.fs" />
    <Compile Include="Reader\Customer.fs" />
    <Compile Include="Reader\Account.fs" />
    <Compile Include="Validation\Account.fs" /> 
    <Compile Include="Validation\Customer.fs" />
    <Compile Include="Validation\Ownership.fs" />
    <Compile Include="Graph\Nodes\Account.fs" />
    <Compile Include="Graph\Nodes\Customer.fs" />
    <Compile Include="Graph\Relationships\Ownership.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Data" Version="8.1.14" />
    <PackageReference Include="Neo4j.Driver" Version="6.2.1" />
  </ItemGroup>

</Project>
