<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="Validation\Institution.fs" />
    <Compile Include="Validation\Person.fs" />
    <Compile Include="Validation\Account.fs" />
    <Compile Include="Validation\Customer.fs" />
    <Compile Include="Validation\Ownership.fs" />
  </ItemGroup>

</Project>
