<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Infrastructure\Neo4j.fs" />
    <Compile Include="Infrastructure\Schema.fs" />
    <Compile Include="Reader\Person.fs" />
    <Compile Include="Reader\Customer.fs" />
    <Compile Include="Reader\Account.fs" />
    <Compile Include="Reader\Transaction.fs" />
    <Compile Include="Reader\Institution.fs" />
    <Compile Include="Graph\Nodes\Person.fs" />
    <Compile Include="Graph\Nodes\Account.fs" />
    <Compile Include="Graph\Nodes\Institution.fs" />
    <Compile Include="Graph\Nodes\Customer.fs" />
    <Compile Include="Graph\Nodes\Transaction.fs" />
    <Compile Include="Graph\Relationships\Has_Customer_Record.fs" />
    <Compile Include="Graph\Relationships\Held_At.fs" />
    <Compile Include="Graph\Relationships\Ownership.fs" />
    <Compile Include="GraphData.fs" />
    <Compile Include="Import.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Data" Version="8.2.0" />
    <PackageReference Include="Neo4j.Driver" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AMLGraph.Domain\AMLGraph.Domain.fsproj" />
    <ProjectReference Include="..\AMLGraph.Reporting\AMLGraph.Reporting.fsproj" />
  </ItemGroup>

</Project>
